apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog-rails
  template:
    metadata:
      labels:
        app: blog-rails
    spec:
      containers:
        - name: blog-rails
          image: json0/ruby-reference:1.8
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blog-db-postgresql
                  key: postgresql-password
            - name: DATABASE_HOST
              value: blog-db-postgresql

---

kind: Service
apiVersion: v1
metadata:
  name: blog-rails
  labels:
    app: blog-rails
spec:
  selector:
    app: blog-rails
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blog-rails
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - rails-blog.apps.jb-test-6.cloud-platform.service.justice.gov.uk
  rules:
  - host: rails-blog.apps.jb-test-6.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: blog-rails
          servicePort: 3000
